name: Codify Gitea Action
run-name: Codify
on:
  issues:
    types: [opened,assigned]
  issue_comment:
    types: [created]
defaults:
  run:
    shell: cmd

jobs:
  Gitea-Issue-Action:
    runs-on: windows
    steps:
      - run: agent.runner.cmd

