name: Gitea Issue Action
run-name: Codify
on:
  issues:
    types: [opened,assigned]
  issue_comment:
    types: [created]
defaults:
  run:
    shell: cmd

jobs:
  Gitea-Issue-Action:
    runs-on: windows
    steps:
      - run: pushd "%CODIFY_RUNNER_PATH%" && run.ai-agent.codify.cmd && popd

